log4j.rootCategory=INFO, console
log4j.appender.console=org.apache.log4j.ConsoleAppender
log4j.appender.console.target=System.err
log4j.appender.console.layout=org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern=%d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n

# 将常用包级别设置为 INFO（保留较详细的信息）
log4j.logger.org.apache.hadoop=INFO
log4j.logger.org.apache.spark=INFO
log4j.logger.org.eclipse.jetty=INFO
log4j.logger.org.apache.spark.storage=INFO
